print_slow("it's a beautiful day outside. birds are singing, ", 0.01)
sleep(1)
print_slow("flowers are blooming... \n", 0.02)
sleep(1)
print_slow("on days like these, \n", 0.03)
sleep(1)
print_slow("kids like you...\n", 0.07)
sleep(1.5)
print_slow("Should be burning in hell.", 0.1)